// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace cykel.chsk.se.Controllers {
    public partial class BundlesController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BundlesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BundlesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Scripts() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Scripts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Styles() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Styles);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BundlesController Actions { get { return MVC.Bundles; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Bundles";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Bundles";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Scripts = "Scripts";
            public readonly string Styles = "Styles";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Scripts = "Scripts";
            public const string Styles = "Styles";
        }


        static readonly ActionParamsClass_Scripts s_params_Scripts = new ActionParamsClass_Scripts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Scripts ScriptsParams { get { return s_params_Scripts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Scripts {
            public readonly string version = "version";
        }
        static readonly ActionParamsClass_Styles s_params_Styles = new ActionParamsClass_Styles();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Styles StylesParams { get { return s_params_Styles; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Styles {
            public readonly string version = "version";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_BundlesController: cykel.chsk.se.Controllers.BundlesController {
        public T4MVC_BundlesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Scripts(string version) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Scripts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "version", version);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Styles(string version) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Styles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "version", version);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
